version: '3.8'

services:
    backend:
        build: ./backend
        container_name: node_project
        ports:
            - '3001:3000'
        environment:
            POSTGRES_USER: dbpgnode
            POSTGRES_PASSWORD: dbpgnode
            POSTGRES_DB: dbpgnode
        networks:
            - app-node-network

    db:
        image: postgres:latest
        container_name: node_postgres
        ports:
            - '4000:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-node-network
            - pg-admin-network

    nginx:
        image: nginx:alpine
        container_name: node_nginx
        ports:
            - '9001:80'
        depends_on:
            - backend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-node-network

networks:
    app-node-network:
        driver: bridge
    pg-admin-network:
        driver: bridge
